INSERT INTO TB_ROUTE_PLAN
(ID_ROUTE_PLAN, NM_ROUTE_PLAN, NM_VEICULO_ID, NR_PARADAS_ATENDIDAS, FLG_ANDAMENTO)
VALUES
(100, 'GreenMile/Moqueca/RioMar', '12345', 0, 'PENDENTE');

INSERT INTO TB_ROUTE_PLAN
(ID_ROUTE_PLAN, NM_ROUTE_PLAN, NM_VEICULO_ID, NR_PARADAS_ATENDIDAS, FLG_ANDAMENTO) 
VALUES
(101, 'Madero/Outback/Iguatemi', '12345', 0, 'PENDENTE');

INSERT INTO TB_PLANNED_STOPS 
	(ID_PLANNED_STOP, LAT, LNG, DS_DESCRIPTION, VLR_DELIVERY_RADIUS, FLG_ANDAMENTO, NR_PARADAS, FK_ROUTE_PLAN) 
VALUES 
	(100, '-3.762526', '-38.481845', 'GreenMile Brasil', '50', 'ENCAMINHADO', 0, 100);
	
INSERT INTO TB_PLANNED_STOPS
(ID_PLANNED_STOP, LAT, LNG, DS_DESCRIPTION, VLR_DELIVERY_RADIUS, FLG_ANDAMENTO, NR_PARADAS, FK_ROUTE_PLAN)
VALUES
(101, '-3.762526', '-38.481845', 'Restaurante Moqueca', '30', 'ENCAMINHADO', 0, 100);

INSERT INTO TB_PLANNED_STOPS 
(ID_PLANNED_STOP, LAT, LNG, DS_DESCRIPTION, VLR_DELIVERY_RADIUS, FLG_ANDAMENTO, NR_PARADAS, FK_ROUTE_PLAN)
VALUES
(102, '-3.762526', '-38.481845', 'Shopping RioMar', '100', 'ENCAMINHADO', 0, 100);

INSERT INTO TB_PLANNED_STOPS 
(ID_PLANNED_STOP, LAT, LNG, DS_DESCRIPTION, VLR_DELIVERY_RADIUS, FLG_ANDAMENTO, NR_PARADAS, FK_ROUTE_PLAN)
VALUES
(200, '-3.801891', '-38.479433', 'Madero Steak House', '30', 'ENCAMINHADO', 0, 101);
INSERT INTO TB_PLANNED_STOPS
(ID_PLANNED_STOP, LAT, LNG, DS_DESCRIPTION, VLR_DELIVERY_RADIUS, FLG_ANDAMENTO, NR_PARADAS, FK_ROUTE_PLAN)
VALUES
(201, '-3.741173', '-38.469695', 'Outback', '30', 'ENCAMINHADO', 0, 101);
INSERT INTO TB_PLANNED_STOPS
(ID_PLANNED_STOP, LAT, LNG, DS_DESCRIPTION, VLR_DELIVERY_RADIUS, FLG_ANDAMENTO, NR_PARADAS, FK_ROUTE_PLAN)
VALUES
(202, '-3.756742', '-38.488745', 'Iguatemi Fortaleza', '100', 'ENCAMINHADO', 0, 101);
